### PR TITLE
aphabetically ordered countries according to translations

### LINKED ISSUE #112: Tax deductible countries sorted wrongly for other languages as English
**Describe the bug**
As the sorting of tax deductible language is done by the English country names from the deprecated names in file https://github.com/Plant-for-the-Planet-org/planet-donations/blob/develop/src/Utils/countriesData.json, the sorting is wrong for other languages as e.g. German:

This should be fixed by sorting by the translations at https://github.com/Plant-for-the-Planet-org/planet-donations/blob/794ea789e1be2b5c831e67087d6e1331a238f70a/src/Donations/Micros/TaxDeductionCountryModal.tsx#L35-L46 as e.g. done at https://github.com/Plant-for-the-Planet-org/planet-donations/blob/794ea789e1be2b5c831e67087d6e1331a238f70a/src/Utils/countryUtils.ts#L62-L73

The error got introduced at https://github.com/Plant-for-the-Planet-org/planet-donations/pull/111#discussion_r697595878, but my review was pending and I missed to push it, so the PR got merged before.

**Is it on a Production or Development Build?**
develop

**Screenshots**
Bildschirmfoto 2021-08-30 um 13 48 53

### PR DESCRIPTION
**Pull request by tejassonar**
Fixes #112

@norbertschuler

### CODE REVIEW

File: src/Donations/Micros/TaxDeductionCountryModal.tsx [hunk 1]
```diff
@@ -38,8 +38,8 @@ export default function TaxDeductionCountryModal(props: any) {
       tempCountriesData.push(getCountryDataBy("countryCode", countryCode));
     });
     tempCountriesData = tempCountriesData.sort(function (a, b) {
-      const countryA = a.countryName.toUpperCase();
-      const countryB = b.countryName.toUpperCase();
+      const countryA = t(`country:${a.countryName.toUpperCase()}`);
```
Comment (norbertschuler) [inline src/Donations/Micros/TaxDeductionCountryModal.tsx]: Country translation resources are having the key `.countryCode.toLowerCase()`!

**Review by norbertschuler — COMMENTED** [review]
This could not really have been tested as the resources have not been loaded correctly. Also I added some dependency to the translation to sort the countries newly if the user changes the language.

**Review by norbertschuler — APPROVED** [review]
